spring:
#  http:
#    encoding:
#      charset: utf-8
#      force: false
#      enabled: false
#  mvc:
#    favicon:
#      enabled: false
  application:
    name: euraka-ha


server:
  port: 20001
#  context-path: /euraka-ha
#  ssl:
#        enabled: false
#  error:
#        whitelabel:
#          enabled: false

#
#management:
#  security:
#    enabled: false


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
#    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 15
    serviceUrl:
      defaultZone: http://server2:20002/eureka/,http://server1:20001/eureka/

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds:30
#    hostname: server1
#  client:
#    # 表示是否注册自身到eureka服务器
##    register-with-eureka: false
#    # 是否从eureka上获取注册信息
##    fetch-registry: false
#    registryFetchIntervalSeconds:30
#    service-url:
#    defaultZone:

#spring.boot.admin.url=http://localhost:6677
#management.security.enabled=false

